config/routes.rb
Rails.application.routes.draw do

  root "application#welcome"
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  resources :teams, except: :show
  resources :teams, only: :show do
    resources :player_teams, only: :index
  end
  resources :players, only: :index
  resources :users, only: :show do
    resources :teams, except: :patch
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jobs/application_job.rb
class ApplicationJob < ActiveJob::Base
  # Automatically retry jobs that encountered a deadlock
  # retry_on ActiveRecord::Deadlocked

  # Most jobs are safe to ignore if the underlying records are no longer available
  # discard_on ActiveJob::DeserializationError
end

app/models/player.rb
class Player < ApplicationRecord
    has_many :teams
    has_many :users, through: :teams

    def self.get_guards
      self.where("position LIKE ? ", "G")
    end

    def self.get_forwards
      self.where("position LIKE ? ", "F")
    end

    def self.get_centers
      self.where("position LIKE ? ", "C")
    end

    def fullname
      firstName + ' '+  lastName
    end

end

app/models/player_team.rb
class PlayerTeam < ApplicationRecord
  belongs_to :team
  belongs_to :player, optional: true

end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  has_many :player_teams
  has_many :players, through: :player_teams

   validates :team_name, uniqueness: true, presence: true
   validate :minimum_three_players

     accepts_nested_attributes_for :player_teams, :reject_if => proc {|attributes| attributes.any?{|k, v| v.blank? if k == "player_id"}}

    def get_captain
      self.player_teams.find_by(captain: true).player
    end

    def minimum_three_players
      if self.player_teams.length != 3
        errors.add(:players, "must have three players on a team")
      end
    end

  end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:github]

  has_many :teams
  has_many :players, through: :teams

  validates :password, :presence => true,
                        :confirmation => true,
                        :length => {:within => 6..40},
                        :on => :create

  validates :email, uniqueness: true
  validates :email, presence: true

  def self.create_from_github_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create! do |user|
      user.email = provider_data.info.email || "github@test.com"
      user.password = Devise.friendly_token[0, 20]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def welcome

  end


end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController

  def github
    @user = User.create_from_github_data(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user
    else
      flash[:error] = "There was a problem signing you in through Github. Please register or try signing in later."
      redirect_to new_user_registration_url
    end
  end

  def failure
    flash[:error] = "There was a problem signing you in. Please register or try signing in later."
    redirect_to new_user_registration_url
  end
  
end

app/controllers/player_teams_controller.rb
class PlayerTeamsController < ApplicationController

  def index
    if current_user
      @teams = current_user.teams
      @player_teams = PlayerTeam.where(:team_id => params[:team_id])
    end
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @guards = Player.get_guards
    @forwards = Player.get_forwards
    @centers = Player.get_centers
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
 before_action :authenticate_user!

  def index
    if params[:user_id]
      @teams = current_user.teams
      @players = current_user.players
    end
  end

  def create
    @new_team = current_user.teams.build(team_params)
    if @new_team.save
      redirect_to user_team_path(current_user, @new_team)
    else
      @new_team.player_teams.build
      render :new
    end
  end

  def new
    @team = Team.new
    @team.player_teams.build
    @team.player_teams.build
    @team.player_teams.build
  end

  def show
    get_team
    @player_teams = @team.player_teams
  end

  def edit
    get_team
    if current_user.teams.include?(@team)
      render :edit
    else
    redirect_to user_teams_path(current_user)
    end
  end

  def update
    get_team
    if @team.update(team_params)
      redirect_to user_team_path(current_user, @team)
    else
    render :edit
    end
  end

  def destroy
    get_team
    @team.destroy if current_user.teams.include?(@team)
    redirect_to user_teams_path(current_user)
  end

  private

  def get_team
    @team = Team.find_by(id:params[:id])
  end

  def team_params
    params.require(:team).permit(:team_name, :player_teams_attributes => [:player_id, :captain, :id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/player_teams_helper.rb
module PlayerTeamsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/welcome.html.erb
<header class="masthead">
    <div class="container h-100">
      <div class="row h-100">
        <div class="col-lg-7 my-auto">
          <div class="header-content mx-auto">
<h2>NBA 3-on-3 Fantasy Team Creator</h2>
<%= image_tag("bron.jpg", width: 500, class: "img-responsive center-block") %>

app/views/layouts/_error.html.erb
<div id="error_explanation">
    <h2>
      <%= pluralize(obj.errors.count, "error") %>
      prohibited this team from being saved:
    </h2>

    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FantasyBasketball</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'page_styles', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="navbar navbar-expand-lg navbar-light fixed-top">
    <%if !user_signed_in?%>
    <%= link_to "Login | Signup", new_user_session_path %>
    <%else%>
    <%= link_to "Available Players |", players_path %>
      <%= link_to "Dashboard |", user_teams_path(current_user) %>
    <%= link_to "Create A Team |", new_user_team_path(current_user) %>
    <%= link_to "Full Roster |", team_player_teams_path(current_user) %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <%end%>
  </div>
    <%= yield %>
  </body>

</html>

app/views/player_teams/index.html.erb
<div class="col-lg-6">
      <div class="feature-item">
          <div class="container h-100">
            <section class="contact bg-primary">
                    <%= image_tag("giannis.jpg", width: 400, class: "img-responsive center-block") %>
<br>
<%@teams.each do |t| %><br>
<%=  link_to t[:team_name], user_team_path(current_user, t)  %> <br>
<%@player_teams = PlayerTeam.where(:team_id => t.id)%>
<% t.players.each do |ply| %><br>
<%=  ply.firstName + ' ' + ply.lastName + ", "   + "Position: " + ply.position %>
<%   if @player_teams.find_by(:player_id => ply.id).captain %>
  <b>  ** Captain ** </b>
<% end %>
  <br>  <% end %>
<% end %>
<br>

app/views/players/index.html.erb
<div class="col-lg-6">
      <div class="feature-item">
          <div class="container h-100">
            <section class="contact bb-primary" id="contact">
                <div class="section-heading">

<div class="bb">
<h2> Plan your future roster here! </h2>
</div>

  <h2>Guards</h2>
  <%= image_tag("hqdefault.jpg", width: 400, class: "img-responsive center-block") %>
  <ul>
    <% @guards.each do |p| %>
    <%=  p.fullname + ' -- ' + p.country %><br/>
    <% end %>
  </ul>

  <h2>Forwards</h2>
    <%= image_tag("durant.jpg", width: 400, class: "img-responsive center-block") %>
    <ul>
      <% @forwards.each do |p| %>
      <%=  p.fullname + ' -- ' + p.country%><br/>
      <% end %>
    </ul>

  <h2>Centers</h2>
  <%= image_tag("embiid.jpg", width: 500, class: "img-responsive center-block") %>
      <ul>
        <% @centers.each do |p| %>
        <%=  p.fullname + ' -- ' + p.country%><br/>
        <% end %>
      </ul>

app/views/players/show.html.erb
<h1> List of NBA Players </h1>

  <ol>
    <% @players.each do |p| %>
    <%=  p.firstName %><br/>
    <% end %>
  </ol>